# Generated by Django 4.0.4 on 2022-05-09 06:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('foto_post', models.ImageField(blank=True, upload_to='fotos/%d/%m/%Y/')),
                ('data', models.DateField(blank=True, default=datetime.datetime(2022, 5, 9, 3, 28, 20, 258458))),
                ('corpo_post', models.TextField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.usuario')),
            ],
        ),
    ]
