# Generated by Django 4.0.4 on 2022-05-09 07:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0001_initial'),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='categoria.categoria'),
        ),
        migrations.AlterField(
            model_name='post',
            name='data',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 5, 9, 4, 15, 40, 506508)),
        ),
    ]
