# Generated by Django 4.0.4 on 2022-05-09 07:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_categoria_alter_post_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='data',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 5, 9, 4, 55, 30, 425913)),
        ),
    ]
